# Generated by Django 4.2.3 on 2023-07-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("r_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="API",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_name", models.CharField(max_length=100, unique=True)),
                ("endpoints", models.TextField()),
                (
                    "allowed_users",
                    models.ManyToManyField(
                        related_name="allowed_apis", to="r_app.users"
                    ),
                ),
            ],
        ),
    ]
