# Generated by Django 4.2.3 on 2023-07-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("r_app", "0002_api"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="tokens",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
