# Generated by Django 4.2.3 on 2023-07-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("r_app", "0003_alter_users_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="tokens",
            field=models.JSONField(default=dict),
        ),
    ]
