# Generated by Django 4.2.3 on 2023-07-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("r_app", "0004_alter_users_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="tokens",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
