# Generated by Django 4.2.3 on 2023-07-27 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("r_app", "0005_alter_users_tokens"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="api",
            name="allowed_users",
        ),
    ]
