# Generated by Django 4.2.3 on 2023-07-27 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("r_app", "0006_remove_api_allowed_users"),
    ]

    operations = [
        migrations.DeleteModel(
            name="API",
        ),
    ]
