# Generated by Django 4.2.3 on 2023-07-27 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("r_app", "0007_delete_api"),
    ]

    operations = [
        migrations.CreateModel(
            name="API",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_name", models.CharField(max_length=100, unique=True)),
                ("endpoints", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("methods", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="ApiUserMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="r_app.api"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="r_app.users"
                    ),
                ),
            ],
        ),
    ]
