# Generated by Django 4.2.3 on 2023-07-28 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("r_app", "0012_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apiusermapping",
            name="api",
        ),
        migrations.RemoveField(
            model_name="apiusermapping",
            name="user",
        ),
        migrations.RemoveField(
            model_name="roleactionmapping",
            name="action",
        ),
        migrations.RemoveField(
            model_name="roleactionmapping",
            name="role",
        ),
        migrations.RemoveField(
            model_name="token",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="users",
            name="role",
        ),
        migrations.DeleteModel(
            name="Action",
        ),
        migrations.DeleteModel(
            name="API",
        ),
        migrations.DeleteModel(
            name="ApiUserMapping",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.DeleteModel(
            name="RoleActionMapping",
        ),
        migrations.DeleteModel(
            name="Token",
        ),
        migrations.DeleteModel(
            name="Users",
        ),
    ]
