# Generated by Django 4.2.3 on 2023-07-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r_app', '0014_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='methods',
            field=models.CharField(max_length=100),
        ),
    ]
